Add version bumping to release workflow. Fix formatting

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -39,33 +39,54 @@ jobs:
           fi
 
   check_pypi:
-      needs: details
-      runs-on: ubuntu-latest
-      steps:
-        - name: Fetch information from PyPI
-          run: |
-            response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
-            latest_previous_version=$(echo $response | grep -oP '"releases":\{"\K[^"]+' | sort -rV | head -n 1)
-            if [ -z "$latest_previous_version" ]; then
-              echo "Package not found on PyPI."
-              latest_previous_version="0.0.0"
-            fi
+    needs: details
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fetch information from PyPI
+        run: |
+          response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
+          latest_previous_version=$(echo $response | grep -oP '"releases":\{"\K[^"]+' | sort -rV | head -n 1)
+          if [ -z "$latest_previous_version" ]; then
+            echo "Package not found on PyPI."
+            latest_previous_version="0.0.0"
+          fi
             echo "Latest version on PyPI: $latest_previous_version"
             echo "latest_previous_version=$latest_previous_version" >> $GITHUB_ENV
 
-        - name: Compare versions and exit if not newer
-          run: |
-            NEW_VERSION=${{ needs.details.outputs.new_version }}
-            LATEST_VERSION=$latest_previous_version
-            if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -rV | head -n 1)" != "$NEW_VERSION" ] || [ "$NEW_VERSION" == "$LATEST_VERSION" ]; then
-              echo "The new version $NEW_VERSION is not greater than the latest version $LATEST_VERSION on PyPI."
-              exit 1
-            else
-              echo "The new version $NEW_VERSION is greater than the latest version $LATEST_VERSION on PyPI."
-            fi
+      - name: Compare versions and exit if not newer
+        run: |
+          NEW_VERSION=${{ needs.details.outputs.new_version }}
+          LATEST_VERSION=$latest_previous_version
+          if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -rV | head -n 1)" != "$NEW_VERSION" ] || [ "$NEW_VERSION" == "$LATEST_VERSION" ]; then
+            echo "The new version $NEW_VERSION is not greater than the latest version $LATEST_VERSION on PyPI."
+            exit 1
+          else
+            echo "The new version $NEW_VERSION is greater than the latest version $LATEST_VERSION on PyPI."
+          fi
+
+  bump_version:
+    needs: [details]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Fetch full history to avoid issues with tags and branches
+
+      - name: Bump version
+        run: |
+          NEW_VERSION="${{ needs.details.outputs.new_version }}"
+          sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$NEW_VERSION\"/" $GITHUB_WORKSPACE/pyproject.toml
+
+      - uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: Bumping version to ${{ needs.details.outputs.new_version }}
+          branch: bump-version-${{ needs.details.outputs.new_version }}
+          file_pattern: "pyproject.toml"
+          skip_dirty_check: true
 
   setup_and_build:
-    needs: [details, check_pypi]
+    needs: [details, check_pypi, bump_version]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -96,48 +117,48 @@ jobs:
           path: dist/
 
   pypi_publish:
-      name: Upload release to PyPI
-      needs: [setup_and_build, details]
-      runs-on: ubuntu-latest
-      environment:
-        name: release
-      permissions:
-        id-token: write
-      steps:
-        - name: Download artifacts
-          uses: actions/download-artifact@v3
-          with:
-            name: dist
-            path: dist/
+    name: Upload release to PyPI
+    needs: [setup_and_build, details]
+    runs-on: ubuntu-latest
+    environment:
+      name: release
+    permissions:
+      id-token: write
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: dist
+          path: dist/
 
-        - name: Install uv
-          uses: astral-sh/setup-uv@v3
+      - name: Install uv
+        uses: astral-sh/setup-uv@v3
 
-        - name: Publish to PyPI
-          run: uv publish
+      - name: Publish to PyPI
+        run: uv publish
 
 
   github_release:
-      name: Create GitHub Release
-      needs: [setup_and_build, details]
-      runs-on: ubuntu-latest
-      permissions:
-        contents: write
-      steps:
-        - name: Checkout Code
-          uses: actions/checkout@v3
-          with:
-            fetch-depth: 0 # Fetch full history to avoid issues with tags and branches
+    name: Create GitHub Release
+    needs: [setup_and_build, details, bump_version]
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Fetch full history to avoid issues with tags and branches
 
-        - name: Download artifacts
-          uses: actions/download-artifact@v3
-          with:
-            name: dist
-            path: dist/
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: dist
+          path: dist/
 
-        - name: Create GitHub Release
-          id: create_release
-          env:
-            GH_TOKEN: ${{ github.token }}
-          run: |
-            gh release create ${{ needs.details.outputs.tag_name }} dist/* --title ${{ needs.details.outputs.tag_name }} --generate-notes
+      - name: Create GitHub Release
+        id: create_release
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          gh release create ${{ needs.details.outputs.tag_name }} dist/* --title ${{ needs.details.outputs.tag_name }} --generate-notes
